### ISSUE TITLE
Server proxy not running in container

### ISSUE THREAD

**Issue by anderoonies** [jupyterhub/jupyter-server-proxy#121]
I'm running JupyterHub, using Dockerspawner to create containers.
I'm setting up a server proxy using traitlets like this:

```py
c.ServerProxy.servers = {
    'test-server': {
        'command': ['python3', '-m', 'SimpleHTTPServer', '{port}'],
        'absolute_url': False
    }
}
```

Inside the container, I see no process running the test server with `ps aux`.

Am I fundamentally misunderstanding how this plugin works, or just configuring something wrong?

Do `ServerProxy` trailets inside `jupyterhub_config.py` or only `jupyter_notebook_config.py`? Is there a way to set up proxy servers within `jupyterhub_config` or do I need to run notebooks? 

Thanks!

**Comment by ryanlovett** [comment]
The traitlets should go in [jupyter_notebook_config.py](https://jupyter-server-proxy.readthedocs.io/en/latest/server-process.html#specifying-config-via-traitlets). So in your case this file should live inside your singleuser docker containers. In python3 I believe you need http.server rather than SimpleHTTPServer.

This software extends the notebook server and not jupyterhub.

**Comment by ryanlovett** [comment]
Example:
https://github.com/berkeley-dsep-infra/datahub/tree/staging/deployments/prob140/image

**Comment by anderoonies** [comment]
@ryanlovett thanks for the help!
i’m running my own server in the container, not the jupyter notebook server. i assumed this was a configuration for the HTTP proxy, not routing inside the container. with that knowledge i’ll just implement this myself, thank you!!!
