### ISSUE TITLE
Fork the lab extension under JupyterLab?

### ISSUE THREAD

**Issue by blink1073** [jupyterhub/jupyter-server-proxy#158]
cc @ryanlovett @betatim @yuvipanda 

I think the lab extension should be moved under the JupyterLab org so it can be maintained separately.  Any objections?

**Comment by betatim** [comment]
What is the benefit of doing that? My initial thought goes to "now we have twice as many places to go check for bugs and make releases" :-/ This is mostly because it feels like a large proportion of the work in this repo is related to those "overhead" tasks.

If there are people who want to help develop and maintain things we could add them here instead?

**Comment by ryanlovett** [comment]
I'm inclined to agree with @betatim. However, @blink1073, what is your reasoning?

**Comment by blink1073** [comment]
That's fair.  I was thinking from a visibility perspective between the two sets of maintainers.  I was not aware that this extension existed until someone pointed it out today.
