### ISSUE TITLE
permission hell has wrecked my jupyterhub proxy

### ISSUE THREAD

**Issue by jtoa2** [jupyterhub/jupyter-server-proxy#172]
Apologies, if this is a repeat +/-  incomplete question - I am more than happy to be directed to documentation but I honestly don't even know where to start.

So I access a remote jubyterhub notebook at https://<ip>:8080/hub/login. The notebook runs on a user (sam) with limited permissions. I was trying to install a package which required writing to the /opt/anaconda3/... directory, and got a permission 13 error. 

Some searching online suggested that $ chown sam -R /opt/anaconda3 would solve my problems, but has in fact broken my https access . Initially I got a 500 error and so I tried reinstating root as the owner of this directory, which which now refuses to connect via my usual address. 

I am worried about security and so do not want to use the nuclear option of opening access to all users via chmod 777, which I suspect will probably not work anyway. 

Does anyone have any suggestions for what might save me?

**Comment by ryanlovett** [comment]
Closing, because this isn't an issue with jupyter-server-proxy.

You might find more suggestions on the [Jupyter Discourse](http://discourse.jupyter.org/), but a couple of things come to mind:
 - if you have a container-based user environment, fully stop and restart your server to reset the userspace.
 - otherwise delete and reinstall your /opt/anaconda3/ environment
