### ISSUE TITLE
urlparse.quote added in 1.3.0 (#177) cause an issue for paths like static/node_modules/@org/package

### ISSUE THREAD

**Issue by benz0li** [jupyterhub/jupyter-server-proxy#185]
When I pin jupyter-server-proxy to version `1.2.0`, everything works properly again. See https://github.com/cdr/code-server/issues/1452#issuecomment-605617433 for more information.

I'm happy to spin up a Docker container to provide you with the necessary log files for debugging. Which information do you need? How do I get the log files of jupyter-server-proxy?

FYI: I'm running JupyterHub 1.0.0 with JupyterLab 1.2.6.

**Comment by betatim** [comment]
It would be great to get some information on what is broken/doesn't work any more. A likely culprit is some network request or paths in network requests. So the logs from your browsers network inspector tab would be helpful as well.

**Comment by benz0li** [comment]
`client.js` and `requirefs.js` are not found:

**Summary**

> URL: https://[redacted]/user/benz0li/code-server/static/87ebf03eb7889595fbbd64ad2b03e784871e751a/lib/vscode/node_modules/@coder/node-browser/out/client/client.js
> Status: 404
> Source: Network
> Address: [redacted]:443

**Summary**

> URL: https://[redacted]/user/benz0li/code-server/static/87ebf03eb7889595fbbd64ad2b03e784871e751a/lib/vscode/node_modules/@coder/requirefs/out/requirefs.js
> Status: 404
> Source: Network
> Address: [redacted]:443

In comparison to paths that are found, both the above paths contain `@coder`. Maybe `@` causes a problem.

**Comment by consideRatio** [comment]
@benz0li I'm not yet well read up on the jupyter-server-proxy but is on my way to learn more about it in general. And I've just picked up the gist of what code-server does (awesome btw!), and I'm totally in the dark of what it would mean to activate a code server extension and what mechanisms come to play activating a code-server extension.

My understanding of the error you experience is:

1. You have used jupyter-server-proxy to channel traffic through your jupyterhub spawned jupyter server under the path /code-server (/user/benz0li/code-server).
2. There are webrequests made to `user/benz0li/code-server/static/...` but they get 404 errors.

- How is your jupyter-server-proxy configuration for the jupyter server's ability to proxy the /code-server path setup?
- I'm not sure about the setup, but i'm wondering if we have run into a cache like issue or where something got out of sync - for example some node/js stuff in the jupyter server proxied by jupyter-server-proxy on /user/<username>/code-server and the other stuff that requested it. Does the issue persist if you try everything with a clean slate in an incognito window?

**Comment by benz0li** [comment]
@consideRatio Thank you for the feedback. Here are the answers to your questions:

> How is your jupyter-server-proxy configuration for the jupyter server's ability to proxy the /code-server path setup?

See https://gitlab.b-data.ch/jupyterlab/julia/ver/-/blob/master/ver/jupyter_notebook_config.py

> Does it allow for requests to /user//code-server/static to be proxied as well as /user//code-server?

Yes. Other js files are served properly.

> Does the issue persist if you try everything with a clean slate in an incognito window?

Yes. Just tested with a Private Window in Firefox.

**Comment by consideRatio** [comment]
@benz0li I'm reading up more and just noted something that seems odd and want to verify that doesn't cause some issue: https://gitlab.b-data.ch/jupyterlab/julia/ver/-/blame/master/ver/jupyter_notebook_config.py#L53

Should you not pass the return value of the function rather than the function itself, by calling it?

**Comment by consideRatio** [comment]
These are the changes in between 1.2.0 and 1.3.0, I didn't find anything apparent that would cause an issue among it: https://github.com/jupyterhub/jupyter-server-proxy/compare/v1.2.0...v1.3.0

**Comment by benz0li** [comment]
@betatim @consideRatio You may access https://test.jupyter.b-data.ch/ using your GitHub account to do some testing.

Access Code Server and try to start Julia REPL (`Press F1 > Julia: Start REPL`). Instead of starting Julia REPL, only `Activating Extensions...` is shown in the status bar (bottom left).

Worked properly using  jupyter-server-proxy version `1.2.0`.

**Comment by benz0li** [comment]
> These are the changes in between 1.2.0 and 1.3.0, I didn't find anything apparent that would cause an issue like you experience among it: [v1.2.0...v1.3.0](https://github.com/jupyterhub/jupyter-server-proxy/compare/v1.2.0...v1.3.0)
> 
> The 404 message of accessing /user//code-server/anything, is that 404 coming from the jupyter notebook server, or is it coming from the code-server? In other words, did jupyter-proxy-server do its job to proxy traffic successfully but it was code-server that failed to find the resource, or was it jupyter-proxy-server that had failed to proxy towards the code-server and returned 404?

```
[W 2020-03-29 16:21:37.980 SingleUserNotebookApp log:174] 404 GET /user/benz0li/code-server/static/87ebf03eb7889595fbbd64ad2b03e784871e751a/lib/vscode/node_modules/@coder/node-browser/out/client/client.js (benz0li@[redacted]) 4.73ms
[W 2020-03-29 16:21:38.089 SingleUserNotebookApp log:174] 404 GET /user/benz0li/code-server/static/87ebf03eb7889595fbbd64ad2b03e784871e751a/lib/vscode/node_modules/@coder/requirefs/out/requirefs.js (benz0li@[redacted]) 5.84ms
```

**Comment by consideRatio** [comment]
I could inspect and debug this myself and conclude that 404 response comes from code-server, but, that may still be because it was passed a faulty request behind the scenes I think.

### A failing web request
```
Request URL: https://test.jupyter.b-data.ch/user/consideratio/code-server/static/87ebf03eb7889595fbbd64ad2b03e784871e751a/lib/vscode/node_modules/@coder/node-browser/out/client/client.js
Request Method: GET
Status Code: 404
```

## A very similar successful web request
```
Request URL: https://test.jupyter.b-data.ch/user/consideratio/code-server/static/87ebf03eb7889595fbbd64ad2b03e784871e751a/lib/vscode/node_modules/onigasm-umd/release/onigasm.wasm
Request Method: GET
Status Code: 200 
```

My hypothesis is that we have ended up making the "@" symbol part of the request be escaped. So:

1. my browser is making a request to:

```
https://test.jupyter.b-data.ch/user/consideratio/code-server/static/87ebf03eb7889595fbbd64ad2b03e784871e751a/lib/vscode/node_modules/@coder/node-browser/out/client/client.js
```

2: And in 1.2.0 i guess jupyter-server-proxy receives it and passes a request to the code server on this path:

```
/static/87ebf03eb7889595fbbd64ad2b03e784871e751a/lib/vscode/node_modules/@coder/node-browser/out/client/client.js
```

But, in 1.3.0 it perhaps escapes it somehow before it passes it onwards to the code-server, so at least the `@` sign is translated to something else.

```
/static/87ebf03eb7889595fbbd64ad2b03e784871e751a/lib/vscode/node_modules/<something other, like %40>coder/node-browser/out/client/client.js
```

Can you inspect the logs of the code-server started by jupyter-server-proxy? Then we would be able to see what it got from jupyter-server-proxy.

**Comment by benz0li** [comment]
OK. I'll try to get hands on the logs of code-server.

**Comment by consideRatio** [comment]
This PR could perhaps introduced this issue: https://github.com/jupyterhub/jupyter-server-proxy/pull/177

**Comment by consideRatio** [comment]
I'm quite confident this is the issue, I tried using the introduced `urllib.parse.quote` function and conclude that @ is translated to %40 while everything else remains preserved, which is very likely to have caused the issue specifically for the request that contained the `@` symbol.

```python
# this ...
from urllib.parse import quote 
print(quote("/static/87ebf03eb7889595fbbd64ad2b03e784871e751a/lib/vscode/node_modules/@coder/node-browser/out/client/client.js"))

# gives us;
`/static/87ebf03eb7889595fbbd64ad2b03e784871e751a/lib/vscode/node_modules/%40coder/node-browser/out/client/client.js'
```

**Comment by oeway** [comment]
Hi, I am sorry about this. 

I made #177 mainly for supporting characters such as space and other symbols. I thought `urllib.parse.quote` will be just smart enough and only quote those ones. When I check [RFC 3986](https://tools.ietf.org/html/rfc3986#section-2.2), `@` is a reserved character which is not recommended to be used without encoding.

How about `client_path = quote(client_path, safe="/@") ` ? This should solve the this issue, however, I am wondering is there other characters like `@` which we don't want to encode. 

Maybe we should we add all the reserved characters (`; / ? : @ = &`), any idea?

**Comment by consideRatio** [comment]
This is what I think is happening atm:
1: A browser makes a web request that arrives at jupyter-server-proxy. In this step, jupyter-server-proxy receives the request without any modification (right?).
2: jupyter-server-proxy receives it and makes a web request to an unknown server it expose to get a response to pass back, but the path of the request to the unknown server is first subjected to `urllib.parse.quote()`.

Is this correct?

**Comment by consideRatio** [comment]
> Edit: Another thought, we had to do encoding for special characters because the proxy_path we get from the tornado handler was decoded. When we encode it again for sending to the server, we don't know exactly what should be encoded.

Is it correct to say that if we don't know how the server we expose through jupyter-server-proxy will react to a webrequest, we can't ensure we do the right thing, and no matter our choice, we will fail to have a rule that works no matter what?

If we cannot know what is the right way to go, then I think we should delegate this as jupyter-server-proxy configuration for its exposed servers.

In this case, it would be allowed to configure:
1. Should the proxy_path encoded with urllib.parse.quote?
2. What safe chars should be used?

**Comment by consideRatio** [comment]
@oeway I see you work at SciLifeLab in Stockholm btw :) Hello from Uppsala! I presented some Jupyter stuff for interested people at SciLifeLab Uppsala a year ago or so.

If you want help spreading its adoption within Swedish universities, let me know! I've been trying to help that happen a while but without any breakthroughs so far.

**Comment by oeway** [comment]
Thank you @consideRatio ! 

> **What I understand to be happening**
> 
> 1: A browser makes a web request that arrives at jupyter-server-proxy. In this step, jupyter-server-proxy receives the request without any modification (right?).
Not exactly, typically the browser will perform [percent encoding](https://en.wikipedia.org/wiki/Percent-encoding) to make sure the url send to the server is safe. When the Tornado server receives the request, it will decode the url.

For example, if you type `http://127.0.0.1:8080/proxy/9988/hello world` (with a space) and hit enter, you will see the encoded url becomes  `http://127.0.0.1:8080/proxy/9988/hello%20world`.

> 2: jupyter-server-proxy receives it and makes a web request to an unknown server it expose to get a response to pass back, but the path of the request to the unknown server is first subjected to `urllib.parse.quote()`.

Because the url is decoded, we need to encode it again before making the request.

I think it's just a matter of figuring out the correct set of characters to be excluded for the encoding. And they should be applicable for all the exposed servers.

Just found a code snippet which could perhaps do the job:
```python
safe_with_percent = "!#$&'()*+,/:;=?@[]~"
url_clean = urllib.parse.quote(url, safe_with_percent)
```

> If you want help spreading its adoption within Swedish universities, let me know! I've been trying to help that happen a while but without any breakthroughs so far.

Sure I would be happy to help, I will contact you via email for that.

**Comment by consideRatio** [comment]
> Because the url is decoded, we need to encode it again before making the request.

hmmm what is decoded? Let's use your example before.

> For example, if you type http://127.0.0.1:8080/proxy/9988/hello world (with a space) and hit enter, you will see the encoded url becomes http://127.0.0.1:8080/proxy/9988/hello%20world.

Will jupyter-server-proxy receive `/hello world` or `/hello%20world` here? I think it should pass it forward as it got it or do an as minimal encoding as possible to make a valid web request if this is considered invalid to pass it forward like it is. Is the example provided such minimal encoding to make a valid webrequest perhaps?

**Comment by oeway** [comment]
> hmmm what is decoded? Let's use your example before.

Decoded means [this line](https://github.com/jupyterhub/jupyter-server-proxy/blob/315d02982a983dd55c75ddaa89ffd6d562857118/jupyter_server_proxy/handlers.py#L257) `proxied_path` will be `/hello world` instead of `/hello%20world`. When we make the request to the actual server, [this line](https://github.com/jupyterhub/jupyter-server-proxy/blob/315d02982a983dd55c75ddaa89ffd6d562857118/jupyter_server_proxy/handlers.py#L216) the `req.url` must be `http://localhost:9988/hello%20world`, otherwise, it fails with the error shown in the description of #177.

**Comment by consideRatio** [comment]
"Because the url is decoded", is this something out of our control, done before jupyter-server-proxy receives it?

I guess I'm asking, is it out of jupyter-server-proxy's control if it receives `/hello%20world` or `/hello world` if a browser sends a request to `/code-server/hello%20world`?

I understand it as we always receive `/hello world` atm, is this correct? If so, then I think the default is clear: we should quote as little as possible by default, but we should at least ensure we send a valid web request if that disallow for a space for example, we should encode the space to `%20`.

I

**Comment by oeway** [comment]
> "Because the url is decoded", is this something out of our control, done before jupyter-server-proxy receives it?

That's my question previously, from the standard request handler api, it seems we cannot get the raw unencoded url. 

I think the minimal set to avoid encoding is the [reserved characters](https://tools.ietf.org/html/rfc3986#section-2.2), since we want them to still serve their reserved purposes:
`: / ? # [ ] @  ! $ & ' ( ) * + , ;`

In addition we should not encode [un-reserved characters](https://tools.ietf.org/html/rfc3986#section-2.3):
`ALPHA  DIGIT - . _ ~`

Therefore I will propse the following replacement of [this line](https://github.com/jupyterhub/jupyter-server-proxy/blob/315d02982a983dd55c75ddaa89ffd6d562857118/jupyter_server_proxy/handlers.py#L144)
```python
client_path = quote(client_path, safe=":/?#[]@!$&'()*+,;-._~")
```
Will make a PR and see what others think.

**Comment by consideRatio** [comment]
@oeway that sounds excellent! Thank you for your thorough follow up on this!

**Comment by consideRatio** [comment]
```
In [4]: quote??
Signature: quote(string, safe='/', encoding=None, errors=None)
...

In [5]: quote?                                                                                                                                       
Signature: quote(string, safe='/', encoding=None, errors=None)
Docstring:
quote('abc def') -> 'abc%20def'

Each part of a URL, e.g. the path info, the query, etc., has a
different set of reserved characters that must be quoted.

RFC 3986 Uniform Resource Identifiers (URI): Generic Syntax lists
the following reserved characters.

reserved    = ";" | "/" | "?" | ":" | "@" | "&" | "=" | "+" |
              "$" | "," | "~"

Each of these characters is reserved in some component of a URL,
but not necessarily in all of them.

Python 3.7 updates from using RFC 2396 to RFC 3986 to quote URL strings.
Now, "~" is included in the set of reserved characters.

By default, the quote function is intended for quoting the path
section of a URL.  Thus, it will not encode '/'.  This character
is reserved, but in typical usage the quote function is being
called on a path where the existing slash characters are used as
reserved characters.

string and safe may be either str or bytes objects. encoding and errors
must not be specified if string is a bytes object.

The optional encoding and errors parameters specify how to deal with
non-ASCII characters, as accepted by the str.encode method.
By default, encoding='utf-8' (characters are encoded with UTF-8), and
errors='strict' (unsupported characters raise a UnicodeEncodeError).
File:      ~/anaconda3/lib/python3.7/urllib/parse.py
Type:      function
```

I'm not sure why, but this reserved list in the `quote` function's docstring is not matching RFC 3986 that also includes []() for example, but quote is actually encoding those as well, treating them as reserved characters.

Whatever is unreserved is not encoded by quote, so for example:

```
In [26]: quote("aA1-._~")                                                                                                                            
Out[26]: 'aA1-._~'
```

But, characters like åäö would be encoded, just like a space, and just like they are if I write `https://www.google.com/search?q=åäö` in my chrome browser, the chrome browser sends a request to the webserver with the åäö being encoded.

I think the right thing to mark as safe, is therefore:

```
      reserved    = gen-delims / sub-delims
      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
```

So like this:

```
client_path = quote(client_path, safe=":/?#[]@" + "!$&'()*+,;=")
```

But... Because of this note from quote's docstring, which i think is faulty, as ~ is part of the un-reserved characters rather than the reserved, and in py37 it behaves as a non-reserved character also... But anyhow, lets also add that.

```
    Python 3.7 updates from using RFC 2396 to RFC 3986 to quote URL strings.
    Now, "~" is included in the set of reserved characters.
```

So the final suggestion I have now is

```
# quote spaces, åäö and such, but don't quote reserved characters and explicitly ensure
# we don't quote un-reserved characters as py36 version of quote may require it
# ref: https://tools.ietf.org/html/rfc3986#section-2.2
client_path = quote(client_path, safe=":/?#[]@" + "!$&'()*+,;=" + "-._~")
```

**Comment by benz0li** [comment]
Thanks @consideRatio and @oeway for resolving this issue.

**Comment by consideRatio** [comment]
:tada: I made a release (1.3.1) of the python package to pip, conda will follow but it takes a bit of time!
