### ISSUE TITLE
Sync versions of package and lab plugin

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/jupyter-server-proxy#197]
The [docs](https://jupyter-server-proxy.readthedocs.io/en/latest/contributing/release.html#release-checklist) say the lab plugin version should match the python package version:

> We keep these two versions in sync to avoid figuring out a matrix of ‘which version of the python package is compatible with which version of the JupyterLab plugin?’

Circa [support for lab 2.0](https://github.com/jupyterhub/jupyter-server-proxy/pull/174), the lab plugin got a bump to 2.x but the package remained behind at 1.x.

The next release of the package should rectify this, even if there is no leap in functionality.

Related: https://github.com/jupyterhub/jupyter-server-proxy/issues/175

**Comment by consideRatio** [comment]
I think I favor having the npm plugin have its major version follow JupyterLab but having minor/patch versions for it released however we please. JupyterLab extensions It typically needs a major bump when JupyterLab bumps its major version, and having it match JupyterLab will probably be more helpful for all endusers.

Parts contributing to my bias to lock the npm package major version to JupyterLabs major version:
- the npm extension is released under the jupyterlab org, and extensions there typically bump its major along with JupyterLab, if only to signal they are with compatible with the new major version of jupyterlab.
- incrementing the major version in a npm package without actually introducing a breaking change because we made a major version bump of jupyter-server-proxy, adds some friction that isn't needed if there wasn't also a breaking change for the npm package
- symmetrically, if the npm package needs a major release, i don't think it makes sense for the python package to make a major release either - that would cause confusion and force users to read changelogs etc only to see there was no breaking change introduced etc.

I suggest we update the docs to indicate this instead - what do you think?

**Comment by manics** [comment]
It's a balance between maintainability and user friendliness. In practice do you have any feeling for how often a breaking release of one component would be required without a release of the other? In the case of a new JupyterLab release if the NPM package follows semver it's only a major release if it's not backwards compatible. If the server package had a major release I'd have thought that implies a breaking API change or a major new feature, which would therefore require the front-end UI component to also change.

If we keep the separate versions do you have any thoughts on how to automate CI deployments? Options I can think of are:
- Prefix tags with the component (e.g. `pypy-1.2.3`, `npm-4.5.6`)
- Move the NPM package into a separate repo

**Comment by consideRatio** [comment]
If it is agreed to release them decoupled from eachother, as I think we should, I like the idea of `1.2.3` / __`py-1.2.3`__ / `pypi-1.2.3` alongside __`jlab-1.2.3`__ / `npm-1.2.3` on git version tags if we want to automate deployment also.

I favor automatic publishing from git tags, and that we have one for PyPI / Python and one for NPM / JupyterLab extension.

**Comment by manics** [comment]
Resolved by https://github.com/jupyterhub/jupyter-server-proxy/pull/247
