### ISSUE TITLE
Make launching lab/notebook server under test more automated

### ISSUE THREAD

**Issue by bollwyvl** [jupyterhub/jupyter-server-proxy#309]
### Proposed change

As of #298, we're encouraging a contributor to start a `lab` or `notebook` server in [a very particular way](https://github.com/jupyterhub/jupyter-server-proxy/pull/298/files/20f6b99afbab90c6fa2044d0bdc11bd814b1eba1#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055) before trying to test it.

This suggestion:
- wouldn't work on Windows
- requires remembering to think about `notebook` and `lab` (and always choose exactly one)
- isn't _exactly_ how we do it in CI

### Alternative options

- not do anything

### Who would use this feature?

- contributors would get a smoother experience, e.g. 
  - > _To run the tests, run `pytest`_
- CI would be simplified
  - `run: pytest` 
- end users would get a more tested experience under both `lab` and `server`

### (Optional): Suggest a solution

If we moved the starting of the server into CI as a `pytest` fixture, perhaps with [pytest-services](https://pypi.org/project/pytest-services/), the server would be spun up and torn down by `pytest`, and could be reconfigured for certain parts of the test suite.

_Perhaps_ as part of this work, we could parametrize the concept of "the server" to include:

- the port (indeed, get verified unused port every time)
- the `base_url` (since binder/hub deployment is quite real)

Going too far down this road, spinning up thousands of servers up and down is no fun. [`hypothesis`](https://hypothesis.readthedocs.io/en/latest/) might be brought to bear to avoid the combinatoric explosion.

**Comment by consideRatio** [comment]
For reference, I recently saw @minrk [refactored tests in jupyterhub/nbgitpuller so that pytest starts `notebook` and `jupyter_server` for tests referencing a fixture](https://github.com/jupyterhub/nbgitpuller/pull/301/files#diff-3451cc474d5698222168f66a293339a6bd296ee2c56f56409866bbae99917a79R50-R97), and I thought it looked like a very neat strategy!

I've not heard about `pytest-services` or `hypothesis` and haven't formed a clear opinion on what I think makes sense for this project. I'm leaning towards avoiding introducing additional tooling unless it comes with sufficient benefits overall though, as most external things comes with some additional learning requirements and chore maintenance for maintainers.

Overall a big :+1: for letting `pytest` handle startup and shutdown of servers via fixtures one way or another though!

**Comment by bollwyvl** [comment]
Sure, a relatively simple form for an isolated server that would work in isolation:

```python
@fixture
@parametrize(["cmd"], ["jupyter-notebook", "jupyter-lab"])
def a_jupyter_server_url(server_name: str, tmp_path: Path) -> Generator[str, None, None]:
    port = get_unused_port()
    server = Popen([cmd, f"--port={port}"], cwd=str(tmp_path))
    yield f"http://127.0.0.1:{port}"
    server.terminate()  # usually better to use the /shutdown API, esp. on windows
```

Even _without_ `hypothesis`, a number of additional `@parametrize` (or consuming more upstream `@fixture`s) could be applied to generate more excursions for `base_url`, loading different config files, etc.

Getting this to work _well_ with coverage collection a bit of a chore, but can be done, and is probably worth it.
